M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu20.04.1} date Mo 26 Jun 2023 22:10:52
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-26T22:10:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X110.409Y-78.113
X110.409Y-83.893
T2
X107.117Y-47.303
X121.117Y-93.553
X135.117Y-47.303
T0
M30
